version: "3.0"
services:
  pathfinder:
    image: eqlabs/pathfinder:latest
    container_name: pathfinder
    volumes:
      - ./l2_execution/data:/usr/share/pathfinder/data
    network_mode: "host"
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=http://127.0.0.1:8545
    ports:
      - 9545:9545
