version: "3.0"
services:
  # beacon_node:
  #     image: sigp/lighthouse:latest
  #     restart: on-failure
  #     volumes:
  #       - ./l1_consensus:/root/.lighthouse
  #     networks:
  #       - shared
  #     ports:
  #       - 9000:9000/tcp
  #       - 9000:9000/tcp
  #       - 5052:5052
  #     command:
  #       - lighthouse
  #       - beacon
  #       - --network=goerli
  #       - --http
  #       - --http-address=0.0.0.0
  #       - --execution-endpoint=http://127.0.0.1:8551
  #       - --execution-jwt=/root/jwt.hex

  geth:
    image: ethereum/client-go
    container_name: geth
    volumes:
      - ./exec_client:/root/.ethereum
    networks:
      - shared
    ports:
      - 30303:30303
      - 8545:8545
    command:
      - --syncmode=snap
      - --http
      - --http.addr=0.0.0.0
      - --ws
      - --ws.addr=0.0.0.0
      - --http.vhosts=*
      - --authrpc.jwtsecret=/root/jwt.hex
      - --goerli

networks:
  shared:
    driver: bridge

  # geth:
  #     image: ethereum/client-go:latest
  #     entrypoint: /bin/sh
  #     volumes:
  #         - ./geth-data:/root/.ethereum
  #         - ./scripts:/root/scripts:ro
  #     ports:
  #         - 30303:30303/tcp
  #         - 30303:30303/udp
  #     env_file: .env
  #     command: /root/scripts/start-geth.sh
  #     restart: on-failure

  # pathfinder:
  #   image: eqlabs/pathfinder:latest
  #   container_name: pathfinder
  #   user: "${UID}:${GID}"
  #   environment:
  #     - RUST_LOG=info
  #     - PATHFINDER_ETHEREUM_API_URL=https://goerli.infura.io/v3/fdf03a10160946b4a0e2b56dbe503d16
  #   ports:
  #     - 9545:9545
  #   volumes:
  #     - ./pathfinder:/usr/share/pathfinder/data

  # validator_client:
  #     image: sigp/lighthouse:latest
  #     volumes:
  #         - ./lighthouse-data:/root/.lighthouse
  #         - ./scripts:/root/scripts:ro
  #         - ./validator_keys:/root/validator_keys:ro
  #     depends_on:
  #         - beacon_node
  #     ports:
  #         - 5064:5064/tcp     # metrics endpoint
  #     env_file: .env
  #     command: sh /root/scripts/start-validator-client.sh
  #     restart: on-failure



